import { CircuitComponent, Wire } from '../store/circuitStore';

export function exportToPNG(): Promise<void> {
  return new Promise((resolve, reject) => {
    const svg = document.getElementById('circuit-canvas');
    if (!svg) {
      reject(new Error('Canvas not found'));
      return;
    }

    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    
    if (!ctx) {
      reject(new Error('Could not create canvas context'));
      return;
    }

    const img = new Image();
    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);

    img.onload = () => {
      canvas.width = img.width || 1200;
      canvas.height = img.height || 800;
      ctx.fillStyle = 'white';
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0);
      
      canvas.toBlob((blob) => {
        if (blob) {
          const link = document.createElement('a');
          link.download = `circuit-${Date.now()}.png`;
          link.href = URL.createObjectURL(blob);
          link.click();
          URL.revokeObjectURL(url);
          resolve();
        } else {
          reject(new Error('Failed to create blob'));
        }
      });
    };

    img.onerror = () => {
      reject(new Error('Failed to load image'));
      URL.revokeObjectURL(url);
    };

    img.src = url;
  });
}

export function exportToSVG() {
  const svg = document.getElementById('circuit-canvas');
  if (!svg) {
    throw new Error('Canvas not found');
  }

  const svgData = new XMLSerializer().serializeToString(svg);
  const blob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.download = `circuit-${Date.now()}.svg`;
  link.href = url;
  link.click();
  
  URL.revokeObjectURL(url);
}

export function exportToJSON(data: { components: CircuitComponent[]; wires: Wire[] }) {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.download = `circuit-${Date.now()}.json`;
  link.href = url;
  link.click();
  
  URL.revokeObjectURL(url);
}

export function exportToHTML() {
  const svg = document.getElementById('circuit-canvas');
  if (!svg) {
    throw new Error('Canvas not found');
  }

  const svgData = new XMLSerializer().serializeToString(svg);
  
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Circuit Diagram</title>
  <style>
    body {
      margin: 0;
      padding: 20px;
      font-family: system-ui, -apple-system, sans-serif;
      background: #f3f4f6;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    h1 {
      margin: 0 0 20px 0;
      color: #111827;
    }
    #circuit {
      width: 100%;
      min-height: 400px;
      border: 1px solid #e5e7eb;
      border-radius: 4px;
      overflow: auto;
    }
    #circuit svg {
      width: 100%;
      height: 400px;
      display: block;
    }
    .footer {
      margin-top: 20px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      color: #6b7280;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Circuit Diagram</h1>
    <div id="circuit">
      ${svgData}
    </div>
    <div class="footer">
      <p>Generated by Circuit Designer on ${new Date().toLocaleDateString()}</p>
    </div>
  </div>
</body>
</html>
  `.trim();

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.download = `circuit-${Date.now()}.html`;
  link.href = url;
  link.click();
  
  URL.revokeObjectURL(url);
}
